sudo: required 
dist: trusty
services:
  - docker
git:
  submodules: false
before_install:
  - wget http://releases.llvm.org/3.9.0/llvm-3.9.0.src.tar.xz
  - tar xf llvm-3.9.0.src.tar.xz
  - wget http://releases.llvm.org/3.9.0/cfe-3.9.0.src.tar.xz
  - tar xf cfe-3.9.0.src.tar.xz
  - mv llvm-3.9.0.src ./lib/llvm
  - mv cfe-3.9.0.src ./lib/llvm/tools/clang
script:
  - cd patch
  - ./apply-patch
  - cd ..
  - ./lib/travis/build.sh emscripten
